### PR TITLE
Fix cryptolib build regression with modern LLVM

### PR DESCRIPTION
**Pull request by korran**
Regression in https://github.com/lowRISC/opentitan/pull/30374

When built with LLVM 23:

```
external/lowrisc_opentitan+/sw/device/lib/base/hardened.h:510:7: error: extension version number parsing not currently implemented
  510 |       ".option push;"
      |       ^
<inline asm>:1:30: note: instantiated into assembly here
    1 |         .option push;.option arch, +zbt0p93;cmov a0, a0, a1, a2;.option pop;
      |                                     ^
In file included from external/lowrisc_opentitan+/sw/device/lib/base/hardened.c:5:
```

### CODE REVIEW

**Comment by korran** [comment]
Alternately, maybe you can do something like 

```C
      // no idea if this is the exact encoding
      asm volatile(
          ".insn r4 0x5b, 0x1, 0x0, %[res], %[c], %[a], %[b]" 
          : [res] "=r"(res)
          : [c] "r"(c), [a] "r"(a), [b] "r"(b));
```

**Comment by korran** [comment]
Before this change:

```
$ bazel build //sw/device/lib/crypto:otcrypto && sha256sum bazel-bin/sw/device/lib/crypto/libotcrypto.a
e9b8325c85584b03eca8c979e478004f9b2a4e65a0f3b876b050a02cb17b8eb8
```

After this change:

```
$ bazel build //sw/device/lib/crypto:otcrypto && sha256sum bazel-bin/sw/device/lib/crypto/libotcrypto.a
e9b8325c85584b03eca8c979e478004f9b2a4e65a0f3b876b050a02cb17b8eb8
```

**Comment by siemen11** [comment]
Hey Kor, thank you for catching this! The cmov is a really nice operation, but moving to ratified instructions might be the cleanest way here.
Maybe we can move to
```
inline uint32_t ct_cmov32(ct_bool32_t c, uint32_t a, uint32_t b) {
#if defined(OT_PLATFORM_RV32)
  uint32_t res;
  uint32_t tmp;
  asm volatile(
      "not %[tmp], %[c];"
      "and %[tmp], %[tmp], %[b];"
      "and %[res], %[c], %[a];"
      "or  %[res], %[res], %[tmp];"
      : [res] "=&r"(res), [tmp] "=&r"(tmp)
      : [c] "r"(c), [a] "r"(a), [b] "r"(b));
  return res;
```

and

```
inline uintptr_t ct_cmovw(ct_boolw_t c, uintptr_t a, uintptr_t b) {
#if defined(OT_PLATFORM_RV32)
  uintptr_t res;
  uintptr_t tmp;
  asm volatile(
      "not %[tmp], %[c];"
      "and %[tmp], %[tmp], %[b];"
      "and %[res], %[c], %[a];"
      "or  %[res], %[res], %[tmp];"
      : [res] "=&r"(res), [tmp] "=&r"(tmp)
      : [c] "r"(c), [a] "r"(a), [b] "r"(b));
  return res;
```

**Comment by korran** [comment]
I'm confused how you want to proceed. This commit reverts back to the original launder-based implementation if the toolchain doesn't support cmov. Are you expecting me to patch in your "new" assembly implementation?

**Review by siemen11 — APPROVED** [review]

**Comment by siemen11** [comment]
> I'm confused how you want to proceed. This commit reverts back to the original launder-based implementation if the toolchain doesn't support cmov. Are you expecting me to patch in your "new" assembly implementation?

You can push your change and I can make a change to the cmov of lib/base
