### PR TITLE
Fix build in top_earlgrey_verilator.cc

### LINKED ISSUE #3926: Verilator build fails in memutils
```
../src/lowrisc_systems_top_earlgrey_verilator_0.1/top_earlgrey_verilator.cc:8:10: fatal error: verilator_memutil_extension.h: No such file or directory
 #include "verilator_memutil_extension.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

https://dev.azure.com/lowrisc/opentitan/_build/results?buildId=24817&view=logs&j=a8b61b66-4668-57fb-dcc3-ba755ef807ae&t=d8303847-c8da-507b-1651-4a69545a97af

Fallout from #3883 most likely.

@rswarbrick can you have a look?

### PR DESCRIPTION
**Pull request by rswarbrick**
This was broken in commit d79ffc2, part of PR #3883 (at one point, I'd
used different names, which I changed again before pushing up).

Fixes #3926.

### CODE REVIEW

**Review by imphil — APPROVED** [review]

**Comment by rswarbrick** [comment]
There are some more CI failures after this patch (to do with a failing assertion). I'm having a look at them now.
