### PR TITLE
[edn,rtl] Fix indices in assertion

### PR DESCRIPTION
**Pull request by rswarbrick**
The existing code wasn't quite right and actually causes a compilation error when you try to push it through Jasper. For a bit more detail, edn_enable_fo is the "edn enable fanout". This is indexed by entries from FatalErr(=1) to LastEdnEntry-1, and doesn't have anything at index zero. (This is what causes the compilation error)

The bug was introduced by a974108, which removed an "enable_q" signal from edn.sv. Looking at the assertions, I think the property that we're talking about is "some of EDN is enabled". To get what I hope is the intended behaviour, I've used a unary OR to combine together all of the enable signals.

The bug is causing N/A entries in the "nightly" FPV tests, discussed here: https://github.com/lowRISC/opentitan/issues/22385#issuecomment-2058225120.

### CODE REVIEW

**Comment by rswarbrick** [comment]
Hmm, my (somewhat guessed) translation of the assertion that was there before is clearly not true! It's causing CI to fail.

@h-filali: Would you mind taking a look at this? (I'm hoping you'll be able to figure out what's going on rather more quickly than me!)

**Comment by vogelpi** [comment]
Thanks for looking into this @rswarbrick and reporting your findings here! I should be able to take care of this (anyway need to do some work on EDN for M3).

**Comment by vogelpi** [comment]
I think I've managed to solve the issue @rswarbrick . EDN intentionally clears the FIFOs upon re-enablement this assertions are observing. This behavior didn't change in the past. What the referenced commit also changed is the condition to disable the assertion. Previously, it stopped after disabling EDN. With the other commit (and your fix) the SVA would only stop after seeing a new EDN request. Obviously, a disablement/re-enablement can come before the next EDN request.

I think I've now managed to fix the issue and directly pushed into your PR. I will now approve the PR but leave the merging to you. Feel free to edit or merge tomorrow.

**Review by vogelpi — APPROVED** [review]
LGTM, but I've further edited the assertion (there was a second bug introduced in the same commit you referenced). I'll leave the merging up to you :-)

**Comment by rswarbrick** [comment]
Thanks for this. I've looked through the change and it looks sensible to me.
