### PR TITLE
[aes, kmac, otbn] Fixes for pre_syn Yosys synthesis flows

### PR DESCRIPTION
**Pull request by vogelpi**
This PR contains a couple of relevant fixes to re-enable the Yosys synthesis flow for KMAC and to make the produced netlist more suitable for analysis SCA countermeasures using the [PROLEAD](https://github.com/ChairImpSec/PROLEAD) tool.

This is contributes to the overall penetration testing effort.

### CODE REVIEW

**Comment by nasahlpa** [comment]
Thanks for working on this!

Is there a recommended version of sv2v? I get this error when running `syn_yosys.sh`:
```console
22. Executing Verilog-2005 frontend: syn_out/aes_2023_12_12_15_01_23/generated/aes_prng_masking.v
syn_out/aes_2023_12_12_15_01_23/generated/aes_prng_masking.v:89: ERROR: Failed to detect width of signal access `$func$\gen_counter.sv2v_cast_64FBD$syn_out/aes_2023_12_12_15_01_23/generated/aes_prng_masking.v:89$5992$\gen_counter.sv2v_cast_64FBD'!
Failed to synthesize RTL with Yosys
```
yosys: 0.9 (git sha1 1979e0b)
sv2v: v0.0.11-28-g81d8225

Not sure where the problem actually comes from.

**Review by rswarbrick — APPROVED** [review]

**Comment by vogelpi** [comment]
> Thanks for working on this!
> 
> Is there a recommended version of sv2v? I get this error when running `syn_yosys.sh`:
> 
> ```
> 22. Executing Verilog-2005 frontend: syn_out/aes_2023_12_12_15_01_23/generated/aes_prng_masking.v
> syn_out/aes_2023_12_12_15_01_23/generated/aes_prng_masking.v:89: ERROR: Failed to detect width of signal access `$func$\gen_counter.sv2v_cast_64FBD$syn_out/aes_2023_12_12_15_01_23/generated/aes_prng_masking.v:89$5992$\gen_counter.sv2v_cast_64FBD'!
> Failed to synthesize RTL with Yosys
> ```
> 
> yosys: 0.9 (git sha1 1979e0b) sv2v: v0.0.11-28-g81d8225
> 
> Not sure where the problem actually comes from.

Thanks for your reviews @nasahlpa and @rswarbrick . You should probably use a newer Yosys version. I am using version 0.36. It's a bit unfortunate that the README.md points to the Ibex README which still lists 0.9 as minimum requirement. However, changing this is a bit tedious as the README.md is vendored in via the Ibex repo.

**Comment by nasahlpa** [comment]
Ah, thanks for the clarification. Synthesis works with yosys 0.36.

**Review by nasahlpa — APPROVED** [review]
