### PR TITLE
[openocd] add openocd patch to work with modern GCC 13.2.0

### PR DESCRIPTION
**Pull request by timothytrippel**
OpenOCD is vendored-in and built from source in our repo. The build started failing recently when the host toolchain was updated on some machines. This adds a patch to fix the compilation error.

### CODE REVIEW

**Review by cfrantz — APPROVED** [review]

**Review by jwnrt — APPROVED** [review]
LGTM

I see this was fixed upstream, so we can drop this patch on the next OpenOCD release.

https://github.com/openocd-org/openocd/commit/00603bf15638347256b1c330bafbeaef0d4d8287
