### ISSUE TITLE
Upstream precompiled hugo binary doesn't work with RHEL6

### ISSUE THREAD

**Issue by imphil** [lowRISC/opentitan#914]
*Note: Please use this bug to discuss the specific topic of Hugo on RHEL6. The question about supporting RHEL6 at all is discussed in #313.*

The 0.59 hugo static binary from https://github.com/gohugoio/hugo/releases doesn't work on RHEL6. RHEL6 comes with glibc 2.12. This makes it impossible for contributors on RHEL6 to build or test our documentation flow. Non-building documentation will fail CI, but without the ability to perform the same steps locally developer productivity is severely impacted.

```
[centoslive@livedvd Downloads]$ ./hugo
./hugo: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./hugo)
./hugo: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./hugo)
./hugo: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ./hugo)
./hugo: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by ./hugo)
./hugo: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./hugo)
```

Reported by @rasmus-madsen 

I'm not aware of any easy workarounds here.

**Comment by gkelly** [comment]
I think this issue is better described as "The automatically-downloaded binary distribution of hugo doesn't work in RHEL6".

It should be pretty easy to get and close hugo on RHEL6 if you have a recent Go version installed.

**Comment by gkelly** [comment]
> I think this issue is better described as "The automatically-downloaded binary distribution of hugo doesn't work in RHEL6".
> 
> It should be pretty easy to get and build hugo on RHEL6 if you have a recent Go version installed.

**Comment by imphil** [comment]
You're right of course. I've changed the title to better reflect that.

Can we come up with instructions how to compile hugo for RHEL6 that @rasmus-madsen can use? Or alternatively, can we compile Hugo for them and provide a binary for these systems?

**Comment by eunchan** [comment]
https://github.com/gohugoio/hugo#fetch-from-github If golang is installed, this should suffice.

**Comment by gkelly** [comment]
With Go 1.11 or above installed it should just be:

```
git clone https://github.com/gohugoio/hugo
cd hugo
go install -tags extended
```
That will take care of getting the dependencies and building everything.  I don't think we should get into the business of distributing hugo binaries if we can avoid it.

**Comment by gkelly** [comment]
> https://github.com/gohugoio/hugo#fetch-from-github If golang is installed, this should suffice.

You need to make sure you specify `-tags extended` to either the build or install command or you won't get hugo-extended.

**Comment by asb** [comment]
I think the non-extended hugo version may work? Is the SCSS processing the only hugo-extended feature we're using right now?

**Comment by gkelly** [comment]
> I think the non-extended hugo version may run on CentOS 6? Is the SCSS processing the only hugo-extended feature we're using right now?

Yes, the SCSS pipeline is the only thing we're depending on from hugo-extended currently.  But it looks like a glibc version mismatch, I'm not sure if the non-extended version is built sufficiently differently to make that not an issue.

**Comment by imphil** [comment]
RHEL6 doesn't package go; I'll try if the go binary release works on RHEL6.

**Comment by gkelly** [comment]
I think a lot of people use the [binaries](https://golang.org/dl) for Go anyway, just because they roll faster than the distros.  Now, those Go binaries might have the same issue...

**Comment by eunchan** [comment]
> > https://github.com/gohugoio/hugo#fetch-from-github If golang is installed, this should suffice.
> 
> You need to make sure you specify `-tags extended` to either the build or install command or you won't get hugo-extended.

Thanks for the correction :+1:

**Comment by imphil** [comment]
Status update:

- The go binary works on RHEL6.
- Hugo without extended compiles on RHEL6.
- Hugo 0.59 extended depends on libsass, which does not compile with GCC 4.4.7 shipped with RHEL6:

```
# github.com/wellington/go-libsass/libs
In file included from ../libsass-build/ast.cpp:2,
                 from unity.cpp:4:
../libsass-build/ast.hpp: In member function ‘virtual size_t Sass::Vectorized<T>::hash()’:
../libsass-build/ast.hpp:336: error: expected initializer before ‘:’ token
../libsass-build/ast.hpp:339: error: expected primary-expression before ‘}’ token
../libsass-build/ast.hpp:339: error: expected ‘;’ before ‘}’ token
../libsass-build/ast.hpp:339: error: expected primary-expression before ‘}’ token
.....
```

Since the we don't support compiling our host software with GCC 4.4.7 either we need to look into a way to provide a newer GCC toolchain for these environments anyways.

@rasmus-madsen @martin-lueker how do you obtain a newer GCC version at the moment to meet the documented system requirements (https://docs.opentitan.org/doc/ug/install_instructions/#system-requirements)?

**Comment by asb** [comment]
I just checked on CentOS 6.8, it's a hugo-extended issue. The normal hugo seems fine.

The go binary is fine, but `go install -tags extended` fails with the CentOS 6.8 gcc 4.4.7 (this is below our minimum requirements).

Installing the devtoolset-6 software collection and enabling that allows `go install -tags extended` produces a hugo-extended that appears to work fine.

**Comment by rasmus-madsen** [comment]
@imphil we need to go through our IT support and have them install the GCC for us which requires jumping through a lot of hoops.

I will get back to you

**Comment by asb** [comment]
> That will take care of getting the dependencies and building everything. I don't think we should get into the business of distributing hugo binaries if we can avoid it.

If we were able to give truly trivial instructions then I'd agree, but given it's a bit more involved by that and that we want ensure those instructions keep working, it might be less work overall to put up a fork of the hugo repo under lowRISC that builds a CentOS version via CI.

[Assuming we do support CentOS 6. As noted in #313, it's no longer officially supported for 2019.x Vivado versions]

**Comment by rasmus-madsen** [comment]
@imphil @asb 
Looks like I am getting a RHEL7 workstation dedicated for this later this week.
I tested the inital setup today and it works with the Hugo binary.

I will let you know more once IT has confirmed the multiuser version is available and we have had a chance to verify that it works.
but that should remove the need for RHEL6 support at least from WDC side

**Comment by rasmus-madsen** [comment]
@imphil we now have a local workaround  so we can compile hugo documents.
I think we can close this ticket?

**Comment by imphil** [comment]
What's the local workaround? Use RHEL7? In this case, we can close this and update our system requirements to RHEL7.

**Comment by rasmus-madsen** [comment]
@tunghoang290780 can you update imphil what the fix was to get the binary working?

**Comment by rasmus-madsen** [comment]
@imphil  no Tung got it working with RHEL6 somehow.
I am still working on RHEL7 unfortunately is a different beast which requires new installation and scripts for all our tools

**Comment by rasmus-madsen** [comment]
@imphil can we close this? - we are still using the workaround.
and unfortunately we are still stuck with RHEL 6.
but I don't think there is any active effort on making a permanent fix .
